# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
dist: trusty
cache: packages
latex: false

r_github_packages:
  - hadley/devtools@efa894ffa
  
jobs:
  include:
  - r: 3.4


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"

after_success:
  - Rscript -e 'covr::codecov()'
